---
title: "LANDFIRE's Open Office Hour Resouces"
author: The Nature Conservancy's LANDFIRE team
date: "February 25, 2021"
output:
  memor::pdf_memo:
    logo: "logo.jpg"
    logo_height: 2.5cm
    use_profile: false
    company:
      name: LANDFIRE
      address: www.landfire.gov
      e-mail: technical questions - helpdesk@landfire.gov; general questions - meg.dettenmaier@tnc.org
    short_title: Wildlife and LANDFIRE data  
    confidential: false
---
# LANDFIRE Open Office Hours

LANDFIRE is a multi-partner program producing and delivering over two dozen datasets and hundreds of ecological models that depict vegetation and fire conditions, past and present. These monthly LANDFIRE Office Hours provide a place to learn a LANDFIRE-based skill, discuss LANDFIRE data use and build community.

[Watch the February 25, (Informal) Open Office Hours](https://youtu.be/p4ls0uRebNY)

# LANDFIRE product use in wildlife research

LANDFIRE spatial data and Biophysical Settings descriptions have been used in projects focused
on wildlife of almost any size, ranging from insects to bison.
Some of the ways researchers use LANDFIRE products include:

• Combining LANDFIRE datasets to build habitat models, as in this paper examining Northern
Goshawk landscape use [(Bruggemand et al., 2014)](https://meridian.allenpress.com/rapt/article/48/3/228/436481/Factors-Related-to-Northern-Goshawk-Landscape-Use)

• Mapping a particular vegetation type, using LANDFIRE as one of many datasets [(Pearman-
Gillman et al., 2020)](https://pdfs.semanticscholar.org/5d4b/ca01dbfdfebea6288e14884d10b9f1637bfc.pdf).

• Reclassifying LANDFIRE Existing Vegetation Types to match habitat selection needs [(Burdette
et al., 2010)](https://esajournals.onlinelibrary.wiley.com/doi/pdfdirect/10.1890/ES10-00005.1).

• Extracting particular vegetation types as inputs for habitat models including machine learning
methods [(Shoemaker et al., 2018)](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.3936).

For this month’s open office hour we focused on the BRAT [Beaver Restoration Assessment Tool](https://brat.riverscapes.xyz/),
inspired partially by this article “[How beavers became North America’s best firefighter](https://www.nationalgeographic.com/animals/article/beavers-firefighters-wildfires-california-oregon#:~:text=This%20beaver%2Ddammed%20wetland%20in,for%20other%20species%20during%20wildfires.)”, by Ben
Goldfarb (National Geographic) and also by the great work of the [Ecogeomorphology and Topographic
Analysis Lab](http://etal.joewheaton.org/) at Utah State University.



# From our conversation. [Watch](https://youtu.be/p4ls0uRebNY)

1. Timestamp: 11:15 min., Sam Cox using NAIP imagery to classify conifers, does LF exist in discrete sets by time period? Could he look at LF as it was 4-5 yrs ago? Can we use it to look at change over time?

• Utah [BRAT](https://brat.riverscapes.xyz/) team has used LF data in this way, will we go the same route as [Rangeland Analysis Platform](https://rangelands.app/)?

• Timestamp: 19:15 min., Qu: Is disturbed only burned? (A: No) [Disturbance layers](https://www.landfire.gov/disturbance.php)

2. Version comparison document is coming out soon

3. Plans are for future delivery more frequently with less latency (plans for 2019L)

4. Timestamp: 23:40 min., Sean McEldery, telling disturbance "story" by sequencing LANDFIRE data

5. Timestamp: 31:47 min., Mohamad Alipour: clarification on what's included and what's not included in Remap (specifically during intermediate years) [Lidar in Remap](https://www.landfire.gov/documents/5813-SiviLaser-JLong.pdf). Contact Kori Blankenship with more questions: kblankenship@tnc.org


# General LANDFIRE links
We provide several ways to learn about LANDFIRE including:

* Main [LANDFIRE Website](www.landfire.gov)
* [LANDFIRE on Twitter](https://twitter.com/nature_LANDFIRE)
* On [YouTube](https://www.youtube.com/channel/UCDPBP2fRXsfSBNjnLrzqxUw)
* e-mail us at landfire@tnc.org
* To receive LANDFIRE product news, data updates, resource recommendations, and occasional cartoons every month sign up [here](https://landfire.us9.list-manage.com/subscribe?u=25aeabb346a09aaf1c528f007&id=2f025aaae2)




